### Register a new user
POST http://localhost:5000/graphql
Content-Type: application/json

{
  "query": "mutation {\n  registerUser(input: {username: \"test\", email: \"test@test.nl\", password: \"test1234\", firstname: \"henk\", lastname: \"henkie\", dob: \"2000-01-01\"})\n}"
}

### Login as a user
POST http://localhost:5000/graphql
Content-Type: application/json

{
  "query": "query login {\n  login(input:{email: \"test@test.nl\", password: \"test1234\"}) {\n    token\n  }\n}"
}

> {%
    client.global.set("token", response.body.data.login.token);
%}

### Update a user
POST http://localhost:5000/graphql
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "query": "mutation {\n  editUser(input: {firstname: \"pieter\"}) {\n    user {\n      firstname\n    }\n  }\n}"
}

### Deleta a user
POST http://localhost:5000/graphql
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "query": "mutation {\n  deleteUser\n}"
}
